# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "bluetooth" "amdgpu" ];
  #boot.kernelModules = [ "bluetooth" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/13adcf4c-ee6f-4847-aeca-d14c44c6fff9";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/31FB-4A09";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/blue" = {
    device = "/dev/disk/by-uuid/abbce8f4-26e2-4aef-b83c-327d944ccc88";
    fsType = "ext4";
    options = [
      "nofail"
      "exec"
      "x-gvfs-show"
      "noatime"
      "nosuid"
      "nodev"
      "X-mount.owner=kreator"
    ];
  };



  swapDevices =
    [ { device = "/dev/disk/by-uuid/e1e205e6-84cd-466b-9ff5-c7d9868349ad"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp191s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp196s0f4u1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp192s0.useDHCP = lib.mkDefault true;

  ### I'm putting ROCm stuff here.
  # Lets try out the new The Rock on Sasha :)
  hardware.amdgpu.opencl.enable = true;
  hardware.graphics.enable = true;

  #environment.systemPackages = with pkgs.rocmPackages; [  
  #packages = with pkgs.rocmPackages_6_4; [
    #clr
    #rocblas
    #rocsolver
    #rocm-smi
    #rocminfo
    #rocr-runtime
    #hsakmt
    #amdsmi
    #llvm.llvm
  #];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
